### ISSUE TITLE
4d[Why]为什么要禁止这些事项？

### ISSUE THREAD

**Issue by lufg** [GC4WP/common#10]
## 背景

加入GC4WP，第一时间看到了禁止事项清单。

> * 永远不用中文名来作任何命名
> * 永远不用拼音来作任何命名
> * 永远使用 UTF-8 编码
> * 永远使用 unix 分行
> * 尽可能不使用 全角标点
> * 尽可能使用 sublime text 等现代编辑器
> * 配置编辑器将 tab 替换为 4个空格
...

为什么呢？

## 分析

提问之前先看指南：

* [提问指南](https://github.com/GC4WP/common/wiki/Hb4Ask)
* [向大妈们提问的技巧](https://github.com/GC4WP/common/wiki/How2askDama)

所以我决定先 google。

## 记录

**1.为什么永远不用中文名来作任何命名？**

* 因为丑
* 中文同一个意思可以有多种表达，而各人用词、命名习惯不一样，难以形成共识，不利于团队协作

出处：[GitHub 协作五大业余姿势 | ishanshan's blog](http://ishanshan.top/community/HbGitHubCooperate.html)

**2.为什么永远不用拼音来作任何命名？**

* 因为业余
* 因为不利于团队协作

2.1如何使用英文命名？

看团队如何约定。

出处：[命名用英文，烦恼少大半|团队文档命名指南 | ishanshan's blog](http://ishanshan.top/community/HbDocName.html)

**3.为什么永远使用 UTF-8 编码？**

3.1什么是 UTF-8 编码？

> UTF-8 就是在互联网上使用最广的一种 Unicode 的实现方式。

3.2不用 UTF-8 编码会怎样？

> 世界上存在着多种编码方式，同一个二进制数字可以被解释成不同的符号。因此，要想打开一个文本文件，就必须知道它的编码方式，否则用错误的编码方式解读，就会出现乱码。

这也是为什么有时你打开 txt 文件，发现全是乱码的原因。

出处：[字符编码笔记：ASCII，Unicode 和 UTF-8 - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2007/10/ascii_unicode_and_utf-8.html)

**4.为什么永远使用 unix 分行？**

> Unix系统里，每行结尾只有"<换行>"，即"\n"；Windows系统里面，每行结尾是"<回车><换行>"，即"\r\n"；Mac系统里，每行结尾是"<回车>"。一个直接后果是，Unix/Mac系统下的文件在Windows里打开的话，所有文字会变成一行；而Windows里的文件在Unix/Mac下打开的话，在每行的结尾可能会多出一个^M符号。

出处：[回车和换行 - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2006/04/post_213.html)

**5.为什么尽可能不使用全角标点？**

因为在不支持汉字等语言的计算机上只能使用半角标点（其实这种情况根本就不存在半角全角的概念） 。

出处：[全角_百度百科](https://baike.baidu.com/item/%E5%85%A8%E8%A7%92)

**6.为什么尽可能使用 sublime text 等现代编辑器？**

因为我用的古代编辑器 MacDown 做不到第7条：「配置编辑器将 tab 替换为 4个空格。」

### 未解决问题

1. 如何用 Unix 分行？

## 变更

……

参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by lufg** [comment]
@ZoomQuiet 姿势正确否？

**Comment by ZoomQuiet** [comment]
@lufg 是也乎,(￣▽￣) 非常聪明的行为
将你的思考, 清晰可持续讨论的发布出来
然后, 大家就可以共同嗯哼了...
只是缺少了必要的 issue 分类标签...以及一个时限

是的, 所有 issue ~ 提案都应该有个期限, 以便进入下一个阶段.

@GC4WP/4all

**Comment by lufg** [comment]
@ZoomQuiet 提交 issue 的时候无法写标签和时限…

<img width="997" alt="2017-11-18 22 17 23" src="https://user-images.githubusercontent.com/17220152/32981207-5df4b08e-ccae-11e7-84e7-6be2be9d2f4e.png">

**Comment by sallysong007** [comment]
姿势完美~~~

**Comment by panda-water** [comment]
hah

**Comment by KqHuang** [comment]
Can someone explain to me what this stream is about?        Is it a test of the function?  I m receiving messages like “hah” and “姿势完美”。


Sent from Yahoo Mail for iPhone


On Monday, November 20, 2017, 4:27 PM, panda <notifications@github.com> wrote:


hah

**Comment by ZoomQuiet** [comment]
@KqHuang 可能是误加入组织的,已经从 组织成员中清除

**Comment by KqHuang** [comment]
我不是误加入的。我是好中文二期学员，只是不知道你们这个邮件组在干什么？


Sent from Yahoo Mail for iPhone


On Monday, November 20, 2017, 9:36 PM, Zoom.Quiet <notifications@github.com> wrote:


@KqHuang 可能是误加入组织的,已经从 组织成员中清除

**Comment by lanaONearth** [comment]
>mark 一下，大虾厉害
