### ISSUE TITLE
[LOG]好中文第二期成员心得笔记

### ISSUE THREAD

**Issue by BrookSongBrookSong** [GC4WP/common#11]
## 背景
我在简书上面偶然发现 [饕餮思文](http://www.jianshu.com/u/25ea71b006a4) 同学会自发记录在好中文课上学到的心得笔记，内容介于客观记录群聊和主观自我感悟之间。

## 分析
我们需要一个文集，专门收录在作业内容之外，同学在好中文课上的体验。可以是心得，可以是经验教训总结；可以是收获延展，也可以就是自己个性化的课堂笔记。

## 记录
[饕餮思文](http://www.jianshu.com/u/25ea71b006a4)     [葡萄美酒夜光杯-----好中文笔记4](http://www.jianshu.com/p/593db0bcf34e)
[饕餮思文](http://www.jianshu.com/u/25ea71b006a4)      [就想把句子码整齐-----好中文笔记3](http://www.jianshu.com/p/9503100b22af)
[饕餮思文](http://www.jianshu.com/u/25ea71b006a4)      [万千宠爱于一身----好中文笔记2](http://www.jianshu.com/p/a128ff34e89e)

## 变更
文章可以发布在简书上，然后以 简书ID + 简书超链接 的形式记录在本 issue中。
也可以就把文本内容跟贴在本 issue 下面。

- 171118 宋偲瑄 init.
-

**Comment by ZoomQuiet** [comment]
@BrookSongBrookSong 多谢哉
@GC4WP/4all 是也乎,(￣▽￣)
这就是索引的作用...

**Comment by aska2tian** [comment]
虽然能看到，暂时不理解是怎么回事~

**Comment by Wlpin** [comment]
小白进来逛逛，留个痕迹

**Comment by nostarcraft** [comment]
well done.pls go ahead.

**Comment by 263vivi** [comment]
试验一下

**Comment by Evan0827** [comment]
试试可不可以留言

**Comment by Rainbow-77** [comment]
我也试试？不知道是不是算进来了=  =昨天突然点了一个地方就发来好多邮件。。。

**Comment by mengfu1973** [comment]
新手报道，算是进来了吧

**Comment by FTAris** [comment]
151-艾瑞斯-秦皇岛
不吃辣的湖南妹子一枚
英文名:F.T.Aris
简书昵称:东曦子月

**Comment by Lihunan** [comment]
嗯，来留个言，证明我有来过。

**Comment by cactusbug** [comment]
留爪儿

**Comment by SillyFlyingBird** [comment]
testing,... 测试留言

**Comment by carinshen** [comment]
新人报到！留个爪印。

**Comment by wongxxxid** [comment]
我觉得我还是懵的

**Comment by Honey8879** [comment]
我还不会玩这个哦

**Comment by maodoujun2017** [comment]
雁过留痕

**Comment by tcjk11** [comment]
难道我也进来了？

**Comment by seine9** [comment]
我也来过…

**Comment by hhztxws** [comment]
半夜mark一下吼哈哈

**Comment by tcjk11** [comment]
为什么从我的主页上找不到我们组织
