### ISSUE TITLE
试一试

### ISSUE THREAD

**Issue by pumacome** [GC4WP/common#14]
## 背景
~ 阐述 记录/问题/事件/... 发生的背景

## 分析
~ 先给出自己的态度以及尝试

## 记录
~ 原始文案收集

## 变更
~ 记录合并学员建议/增补的主要变动信息

- 171117 ZQ init.
- ... 使用日期 作者 记要 <-- 这种行格式来嗯哼

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by Lihunan** [comment]
试一试
