### ISSUE TITLE
4d[L01E01] 从前是现在

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/common#15]
~ 作业草稿, 内部公示, 修订 4Day 后再发布 jianshu, 欢迎大家给出修改建议 <- 直接回复 Issue 就好

# 标题: 从前是现在

### 目录/纲要

- 从前
    + 偷窥厕所
    + 三线研究所的日常
    + 最喜欢在夜晚私人探险
    + 山,河,水...
- 喜欢
    + 发现有人在半地下仓库养鸡
    + 利用鸡的夜盲症,管理大公鸡的行为
    + 遇到了她,隔壁班的校花
    + 一起从墙洞中挖冬眠的苍蝇来喂小鸡
    + 一起用铅笔盒炸土豆片
    + 一起粘秋蝉烤着香
    + ...
- 一个人
    + 37年过去,回到上海,供职国际集团
    + 无意间发现董事长助理是她
    + 年会,吹乒乓球游戏重新相识
    + 慢慢开始规划未来
    + 核心项目脑机接口的研发
    + 成功了
    + 也发现自己不可以使用
    + 作为第一批数字公民她和精英们走了
- 现在
    + 420年后
    + 作为遥控师, 自愿休眠几个世纪来到人类宇宙的边疆
    + 海参崴的日, 作为能源采集站拥有最紧密的机器人集团以及最高配置的计算集群
    + 为了应对越来越复杂的采集现场
    + 申报成功启动自动繁殖式计算集群生产
- 喜欢
    + 虽然无法长期进入数字地球生活, 但是沉浸同步率却非常高
    + 工作之余, 逐步在数字地球备份中还原了当初三线研究所的一切
    + 一个人从墙洞中挖冬眠的苍蝇来喂小鸡
    + 一个人用铅笔盒炸土豆片
    + 一个人粘秋蝉烤着香
    + ...
- 一个人
    + 在数字地球中漫游时,经常发现隐藏的备份包
    + 在 切尔诺贝利 遗址处,发现了不得的东西
    + 几个世纪前首批数字公民的记忆备份
    + 调集富余的计算资源, 逐步具身化其中4万位精英的记忆体
    + 复活在三线研究所
    + 用最新的时间加速算法,令世界时间过去37年
    + 在这个人类宇宙的边疆,我构造出了基本真实的原来的世界
    + 终于,还是提取了她
    + 一起回到 455 年的那个状态
    + 独自生活在距离全人类最远的所在
    + 并不寂寞
    + ...

## 是也乎

- 171125 起草

**Comment by Rainbow-77** [comment]
程序员的脑洞好可怕QAQ

**Comment by mayo111** [comment]
程序员的内心住着一个宇宙
既渺远又孤独
你偷窥厕所
别人也偷窥你
偷窥到一个精彩的人生，岂不快哉

**Comment by wangyu1356** [comment]
好脑洞

**Comment by ZoomQuiet** [comment]
--> [《GC4L01E01🐙从前的现在》](http://www.jianshu.com/p/6b4a92481ad0)
<-- [dama.md](https://github.com/GC4WP/common/blob/mg3la2/L01E01/dama.md)

DONE as good! 达成/归档/交付ed
