### ISSUE TITLE
draft[L01E01] 红黄蓝

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/common#16]
> 背景
~ 阐述 记录/问题/事件/... 发生的背景

> 10万字写书计划活动

- 大纲要求：请包含【标题】、【副标题】、【目录】三部分内容，题材不限
- 提交日期：12月8日晚23：00之前
- 提交形式：完成后请投稿简书专题“好中文的样子”http://www.jianshu.com/c/6c9915be5f2c
- 投稿要求：请在文末注明“L01E01”

> @323-水天衣-青岛 这两天红黄蓝幼儿园的事情不是挺火的吗？我脑中冒出个想法，能不能写一个故事，这些孩子在童年遭遇了这样的事情，但是却因为政府不作为事情不了了之，他们在成长过程中却承担了各种压力和异样的眼光，然后他们的性格扭曲了，复仇成为了她们生存下去的目标，是的，故事就是她们的复仇故事

是也乎 ╮(╯▽╰)╭

    必须有啊
    刚好红黄蓝三部曲
    每部都比前一部多十万字…

> 所以, 仅仅作为创新梗概内部供给, 哪位学员想用, 嘦支付 42元 即可.

# 标题:红黄蓝

#### 红
~是个男孩

- 军队:…选择最直接的复仇~加入军队
- ~修炼军事技能…
    + 汽车兵开始
    + 因为能烧菜
    + 历经连/团/旅厨师长
    + 通过师长保送入军校研发战地全地形炊事车
    + 自学各种金属加工技能以及作战技巧
- 退役后…用手造狙击步枪
    + 隐藏的炮钢
    + 慢慢手工镗出枪管
    + 使用手工制造的箭形弹
    + 通过滑膛方式发射
    + 电击发液体发射药
    + 整体系统根本不象步枪
    + 好似一种工程测试仪器
    + 经过4年努力, 在张家界深处完成最终调节
    + 射程3700米, 可以洞穿两层砖墙
    + 拆解后, 可以通过机场的安检
    + 只有发射药必须事先用避孕套包好吞入胃中夹带...
- 逐一点杀当年涉及虐待幼童的`叔叔`…
    + 每个月一次
    + 非常规律
- 最终被相似经历的小伙伴出卖惨死
    + 叔叔们的名单/行程
    + 都是过往小伙伴们提供的
    + 但是,当年已经是高官的现在更难追踪
    + 终于冒着暴露的危险,联系上一位有内部消息的伙伴
    + 不料...
- …身后也只是个枪匪
    + 但是, 手造的滑膛狙击枪, 最后列装解放军特种部队
    + 通过无人机发射侦查弹...多年后一次误发射,终于击杀了当初没有杀死的那一名`叔叔`

#### 黄
~就是出卖红的帅哥

- ~他选择了打入敌人内部的策略
- …忍耐着各种非人的磨难
- …从当年令自已肛裂的叔叔身边
- …一张张床爬上去
    + 男女都要服侍好
    + 还得忍受各种变态的要求
    + 对得起良心的只有在送幼童时给予足够的致幻剂, 以免留下清晰的记忆
    + 并自学摧眠术,义务为幼童们关闭记忆
    + ...
- ~终于发现整个 `关系网` 大致全礼貌时
- 意识到其真正的可怕…最后绝望
    + ~虐杀了当年的叔叔后…
    + 静静的自杀~
    + 在当年幼儿园原址的地下
    + 自杀前将收集的资料传给了蓝

#### 蓝
~是其中最漂亮的女孩子

- 因为多次阴道撕裂导致阴蒂受损…实质上被实施割礼…
- 由于这一变故…
    + 蓝远走法国…
    + 经过卓绝的努力
    + 逐步积累各种能力
    + 终于,成为一名超模…
- 才发现几乎所有超模幼儿时都有类似受虐经历…
- 于是在聚光灯下巧妙的利用时装周
    + 创建了 `灭虐营` 地下组织…
    + 逐步推动各国立法阉割恋童癖…
- 并暗地资助两伊逃亡的女生进行军事训教…
    + 夺回 isis 统治的家乡…
    + 独立为自治州…
    + 作为秘密处决恋童癖名人的基地~
    + 在收到 `黄` 的资料时
    + 已经处决了 420 名有案可查的各国政要
    + 唯一没有触及的国家就是天朝
- 最终…发现自己已经变成
    + 只有虐杀小女孩才能有快感时…
    + 蓝选择了公开一切…
    + 并在直播现场~
        * 在十万观众…
        * 二亿网络直播观众面前自杀…

> C'est la vie (´-ι_-｀)

#### 白
~ 当年所有被虐幼童中有一对高智商双胞胎, 白是姐姐

- 出事后, 家庭破裂,白跟了妈妈
- 远走美国, 改嫁后,入藉,爆发学霸气质
- 一直跳级,短短20年, 就成为最年轻的终身教授
- 供职一个私募基金,进行投资分析
- 私下却是很早就成名的 骇客: `白光`
    + 擅长入侵各种公共监视系统
    + 用5年开发成一个 AI
    + 利用 暗网 的资源
    + 开始长年自动收集所有虐童证据
    + 分析整理后的名单和证据都分散备份在全球互联网中
    + 特别是:
        * 卫星的备用系统恢复记忆体尾部
        * 所有汽车行车记录仪的系统盘隐藏空间
        * 必须通过区块链交易形式的全网认证才能取到
- 但是, 一直不敢, 也不知道能将证据提供给谁
    + 曾经尝试通过香港一个民运组织发起诉讼
    + 结果没出4天, 整个组织就消失了
    + 半年后, 从暗网获得了那个组织其中一个主要领导在非洲钻石矿出意外死亡的录像
    + `白` 知道这个世界的恶意是多么的宏大
    + 开始另一项更加隐密的对抗... 
- 终于有一天发现了 `黑`

#### 黑
~ 白是双胞龙凤胎弟弟

- 出事后, 家庭破裂,白跟了爸爸
- 也出国, 只是到了巴西, 在日本自治洲
- 入藉后, 爆发学霸气势
- 在生物遗传领域展现出异常的能力
    + 初中自然课的独立作品就是通过共生系统的设计
    + 令原先不发光的一种水母
    + 结合一种发光的海藻
    + 形成互利的全部生物组织
- 被日本在巴西的最大制药厂吸收, 21岁时,成为独立实验室负责人
    + 从而接触到 731 部队真正的遗产
    + 可行的人体活体基因注入技术
- 在进行厂方的产品研发期间
    + `黑` 私下进行的研发是活体应激式生物毒素施放
    + 希望可以找到一种基因开关
    + 可以令14岁之前的幼童具有天然的毒素合成能力
    + 仅当生殖器官受到意外损害时...
- 可惜这个思路怎么也无法突破
    + 因为一但生殖器官有施毒能力,将是终身有效
    + 终于有天见到壁虎断尾才想通
        * 令一对卵巢或是睾丸具有施毒能力
        * 成年后自身死亡就好
    + 但是, 这种改造属于一种生物器官强化,难以变成可遗传的自然能力
- 通过 `蓝` 的事迹, `黑` 才发现有GAAC(全球反虐童组织)的存在
    + 多方调查后
    + 无意间发现了自己的姐姐

> 于是....

## 变更
~ 记录合并学员建议/增补的主要变动信息

- 171125 微信群中激发而成

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by mayo111** [comment]
红和黄让我想起《无间双龙》，小栗旬和生田斗真演的，一家慈善孤儿院竟然是为了给特权阶级提供器官移植而存在的饲养场，发现真相的一名老师（受派管理此处的女警察）被过来杀人灭口的公安枪杀，目睹全过程的两个孩子从此走上漫长的复仇之路。一个加入黑帮，一个考入刑警队，里应外合，寻找当年的涉案人员复仇。最后两个人回到孤儿院的遗址处，为深爱的老师自杀殉葬。

**Comment by ZoomQuiet** [comment]
@mayo111 这就是你的剧本大纲了哪.非常好
可以是 红黄蓝 的番外

**Comment by YixuanFranco** [comment]
这个黑.......

别人都是事实所逼变态.
他是真的无聊所逼变态.

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
