### ISSUE TITLE
[L01E01] 34次写作练习

### ISSUE THREAD

**Issue by aska2tian** [GC4WP/common#17]
## 背景
> @002-叶猛犸-黑龙江 十万字计划的核心其实是：你想练习什么技能？
> 风景、情绪、结构、对话、还是别的什么？找到你想练习的，以它为中心就好。
> 若是你想练习描写风景，就尝试写写游记；尝试练习对话，就写电视剧剧本，等等等等

> 背景什么的，这不是作业吗！

## 分析
> 受了猛犸君的指引，选择一个尽量明确具体的自我提升目标，就是通过数次练习，学习写故事。
> 选了一些现成的故事或题目，当做命题作文来练习，这是一种偷懒的做法。
> 每篇故事的题材不限，人物不会统一，篇与篇之间也未必有联系。
> 我理解，所谓写作大纲不过是在心里给自己树一座尚未存在碑，然后告诉自己，哥们要一个人一块砖一块砖的把这座碑竖起了。

## 记录
~ 原始文案收集

## 变更
~ 记录合并学员建议/增补的主要变动信息

- 171127 ASKA init.

## 副标题：众生轮回

1. 武松打虎（无意中做了英雄）
2. 风雨山神庙（被逼无奈走了一步险棋）
3. 鲁智深拳打镇关西（貌似鲁莽的生佛）
4. 灰姑娘（善良者一步登天的梦）
5. 白雪公主（天生丽质的罪）
6. 小红帽（对性的恐惧）
7. 尼奥（成为救世主的精神病人）
8. Mr. White（临死前的挣扎）
9. 嫌疑犯X的献身（为了一点光明的牺牲）
10. 杀人回忆（罪犯在眼前却抓不到）
11. 殉难者（无动于衷的施虐）
12. 三只眼的无（无限重生者的痛苦与选择）
13. 虫族小狗（卑微者对未知力量的恐惧）
14. 偷桃（遇到的吞铁球的人）
15. 聂小倩（帮凶的自我救赎）
16. 画皮（如何克制虚伪的坏人）
17. 女相士（无助者对命运的迷信）
18. 矿车（幼时的莫名大炮仗冒险）
19. 阿富的贞操（革命党和丫鬟）
20. 白话杂阿含经1（十四无记）
21. 白话杂阿含经2（无常）
22. 白话杂阿含经3（涅槃）
23. 我所理解的论语十句话1（仁）
24. 我所理解的论语十句话2（中庸）
25. 我所理解的论语十句话3（小人）
26. 生（八苦之一）
27. 老（八苦之一）
28. 病（八苦之一）
29. 死（八苦之一）
30. 怨憎会（八苦之一）
31. 爱别离（八苦之一）
32. 求不得（八苦之一）
33. 五蕴盛（八苦之一）
34. 玄奘取经（瑜伽师地论与永不被理解）

> 有时候想王佩老师未免太实诚了，昨天语音课，今天微信互动，纯肉身上阵。
> 昨天的十万字写作大纲还没完成，六本书还在路上，今天的圣经创世纪和共产党宣言仍未启动。
> 早早完成一个作业吧，后面的还在等着呢~

参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by wangyu1356** [comment]
所以说是个短篇故事集。

**Comment by aska2tian** [comment]
王老师Release了两个文件，都有密码。嘿嘿
