### ISSUE TITLE
demo[L02]翻译奶

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/common#18]
# L02E05.42

> 找出汉语⾥引进的--

## 外来译词
> 至少10个翻译词，比如“民主”

1. 水泥 --> 基因
2. 电脑
3. 软件
4. 内存
5. 函数
6. 纤程
7. 超频
8. 频谱
9. 黑洞
10. 科普

@GC4WP/mg3la2 回复增补各自的嗯哼
可以用表情来代表同意否

**Comment by ZoomQuiet** [comment]
水泥

<-- 音译词?

应该用其它来替代

**Comment by ZoomQuiet** [comment]
同意...

> 基因

**Comment by ysty618** [comment]
大妈：谢谢你，我终于爬进来了。而且网页带翻译了。谢谢谢谢谢谢。

**Comment by ZoomQuiet** [comment]
@ysty618 是也乎,(￣▽￣)
您挑的地儿, 还真的是....

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
