### ISSUE TITLE
[LOG]为什么应当加入好中文写作班

### ISSUE THREAD

**Issue by ZoomQuiet** [GC4WP/common#2]
## 背景
~ 阐述 记录/问题/事件/... 发生的背景

171115 [【直播回听】好中文写作课｜试听MP3_音乐歌曲免费下载-喜马拉雅FM](http://www.ximalaya.com/43552396/sound/58429353/)

现场 `无双` 学员同步 记要

## 分析
~ 先给出自己的态度以及尝试

大妈整体嗯哼为 Issue 公开给后来学员

@GC4WP/4all 

## 记录
~ 原始文案收集

王佩老师第一讲 为什么应当加入好中文写作班

能让你提高心智和文采的唯一的地方。
第一期形成的讲稿要出书。
一。输入
写作的源头
和合技
故事力

二。输出
古典文体
心智写作
修饰意识

阅读和写作的书大多分离。输入的目的是为了输出。阅读的目的是输出，不然知识就进入了黑洞。
市面上不乏一些美文推荐，鉴赏，给孩子的诗，给年轻人的信等等。但只管选文，不能从源头和技巧上对大师的作品进行反向工程。
还有一些书，阿猫阿狗都能写引进版{开始写吧}，这种，我买了之后发现他们唯一的价值就是这四个字而已。内容千篇一律。
还有些书卖的比较巧妙，不说自己是写作书，大家都不感兴趣，聪明人叫故事。例如STORY。原来讲的是标准的编剧书。
还有一些台湾书，擅长演讲和总结。大家很难变成卖点的书他们整理下就可以出了。很畅销，现在转向了写作的领域。
许荣哲等人。入门，练习有一定价值，但是有简单化的风险。写作的东西教条，拆解之后，不追根溯源，学到的只是边角。
好中文强调，做神魂道的东西。文字有大道，翻译有大道的东西。技法技巧技能等都是自动引出的东西。
挖掘下去一定会触及到根本――中文写作的源头在哪里，我们要跟谁学习。重要的问题。

例如，白话文，宋朝以来的宋朝笔记。
四大名著所代表的白话文。民国时期，朱自清，鲁迅？
建国以来的作家？
学习原生的白话文，还是欧化成分的白话文？都是绕不开的问题。
我们第二期推荐了6本书。每周六带领大家阅读。涵盖了我想在半年时间内让大家迅速掌握并了解的能代表好中文各方面，好的侧面的正面的东西。
怎么读都可以。
第一本，英国散文的流变。为什么先从英国讲起？别的语拉美的法语我也不会啊。能贯穿东西的我只能从这个讲。王佐良也是我们可以学习的对象。
第二本，有争议的观点。翻译有大道。有几篇非常著名的文章，70年代作品。反映的问题到今天仍存在。就是要不要欧化的问题。当年还是振聋发聩的。今天来看，当年批评的东西已经成为汉语主流，我们要不要批评？汉语的欧化问题是怎么回事。我们应该站在更广更高的角度去看。
以往白话文来源于五四运动，但是实际上来源于宗教著作。佛经翻译过来之后已经改变了很多汉语的表达。
到了100以前，当欧美传销士在一起翻译和合本的时候对汉语进行大规模改造，对我们的影响至深。1949年之后，大陆台湾香港分成两种文化，我们对马列著作翻译成中文，并全国开始学习，产生深刻影响。以往我们的汉语适合写诗，写散文，不适合写抽象理性思辨的语言。捉襟见肘。但是马列编辑局1949年之后，汉语的表达能力要比过去强大很多。以前汉语不能表达的抽象的，思辨的，西方哲学的内容都能表达的。我们要站在动态的发展的角度看。是在古汉语基础上改造过来的结合了翻译语言不断发展演化的语言。
第三本，很难读，但是好中文的理论基础。申小龙，复旦大学教授。经历坎坷，语言学部分大量用国外资料却没有出处。从此被忽略。其有灼灼的才华。
我们要了解汉语语法和西方语法的不同，汉语语言和欧化语言的不同。找到中国的表达方式。读这本时间会长，我会带领大家读出重点。
最有魅力的地方不是我的讲座也不是这些书。
社群的集体的智慧。匪夷所思的创造性的工作。
大妈，猛犸，沐沐周，安心竹，小七等。
把他们关在一起，不需要教程，都可以创造美好的东西。每个人都是跨学科的。信息流乍看很凌乱，习惯了萃取方式之后能从中得到非常多的精华。超越了我的讲课和交流，珍惜在群里机会，多多参与，学会秒懂达人们的发言。
好中文强调和合技。大家一起合作产生的力量。还有跨文本，超文本，超超文本的阅读。
第四本，story。实际上是讲故事的能力和笔记书。所以作为参考书目。因为故事已经越深入人心，各行业。
举例卖男人肾药的故事。国家成立了基金，1680的药国家补贴1000，现在只需要680。简单的故事，国家向老百姓提供福利的故事，而不是药品的降价。
第五本，杜甫的五城。多看几遍。比文化苦旅天壤之别。文风完全不同。沐沐周说的很好，第一遍干瘪枯燥，但是读两遍之后就泪流满面。
作者是史学家的笔墨，他是唐史专家。少用辞藻煽情。古典的文风。除了这本还有一本男人育儿的书。其他的都是非常专业的专业书。
这些书读完之后就进入输出阶段。
就是我翻译的那本。我用我们中国人的例子和中文写作的实践融合进去。中国人写的和翻译过来的还是有天壤之别的。天然带着一种能量，是通过翻译无法替代的。风格的感觉+好中文写作课。结合经典文风，心智写作
输出将上个新台阶。
极限性的训练，加强这部分的训练。
比如写文章不能出现形容词，叹号，的，了，等。好玩的局限。恰恰戴着镣铐才能尽情舞蹈的地方。
感谢各位抽出半小时时间测试这个平台。10天后11.24日开课的时候大家都来参加。

## 变更
~ 记录合并学员建议/增补的主要变动信息

- 171117 ZQ init.
- ... 使用日期 作者 记要 <-- 这种行格式来嗯哼

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by BrookSongBrookSong** [comment]
第一期学员加入第二期的理由：
1. 大妈 [冲破`海洋般的微笑`~好中文写作课私人体验](http://www.jianshu.com/p/202b98cfea20)
2. 大妈 [`怂怼录`~直播好中文的嗯哼](http://www.jianshu.com/u/3908d6bf439d)
3. 猛犸[要在简书混，你就该参加好中文二期](http://www.jianshu.com/p/3e5b5374da71)
4. 猛犸[关于好中文的几个故事——直播预告](http://www.jianshu.com/p/e5de92b06814)
5. 沐沐周 [游戏之美、沉迷与逃离](http://www.jianshu.com/p/4df077026f30)
6. 当时明月在zh [我眼中的《好中文的样子》及其它](http://www.jianshu.com/p/b7d91daffcad)
7. 偲瑄 [「好中文」我们在第二期，等你来](http://www.jianshu.com/p/672b8fa41e28)

其他同学如果写过，请修改补充。谢谢。

**Comment by ZoomQuiet** [comment]
@BrookSongBrookSong --> [Home · GC4WP/common Wiki](https://github.com/GC4WP/common/wiki)
ARCHIVED be wiki ;-) 归档/收录/提交ed
