### ISSUE TITLE
[LOG]王佩老师分享——好中文的秘密1117

### ISSUE THREAD

**Issue by hhztxws** [GC4WP/common#6]
## 背景
~ 阐述 记录/问题/事件/... 发生的背景
171117 王佩老师直播《好中文的秘密》
现场 `无双` 学员同步 记要

## 分析
~ 先给出自己的态度以及尝试
无双笔记 Issue 公开给后来学员

## 记录
~ 原始文案收集

> 分享正式开始。
介绍下正在做的一个项目和写的一本书。
精华所在。《好中文的秘密》
想跟大家分享的是一些研究语文，研究写作的办法，这些办法是诀窍，不传之秘。
没想到在100多年前大家用的最古老的办法，现在在网络时代借助程序语言做一切很有趣的事情。
之前做了演示，在github上做了文本的对照，请大家朗读了。（暖场部分）
办法的来源——请看图。

![官话和合本中的西方成员](https://user-images.githubusercontent.com/3174106/32974343-32fa12c8-cc38-11e7-8c64-e5240641fc29.jpeg)

![官话和合本中的西方成员](https://user-images.githubusercontent.com/3174106/32974362-5f712c06-cc38-11e7-8694-f13f465f7755.jpeg)

> 第一行是5个人的名字。起了中国人的姓氏，他们在做一件事情，到今年恰好100年——他们在做圣经的现在全世界华人通行的版，和合本。
和合，英文公会的意思。团结的意思。
在和合本诞生之前有很多版本圣经，每个团体每个人都翻译，方言的都有，福州，上海版本的都有。最多的是文言文的。因为中国人的传统，在清末民国初年，不用文言文写的东西不是知识分子的范畴，没人看，传教士想了办法，高价400银元，请中国第一翻译高手严复来翻译圣经。此版本在剑桥图书馆找到了。严复拿钱后，翻译了4章就不干了，非常遗憾。如果能翻译下去，中国宗教史和文学史都会留下重重的一笔。其他传教士也翻译了个文言文的版本。可以对比下。
官话和合本（白话文版）vs严复版。（另见两个文件）
大家读下严复会发现中文美妙的古汉语余韵在经典中发挥的淋漓尽致。
近代以来中国受列强的欺凌，社会发生很大变化。原来读书人儒家的东西在社会上不受欢迎了，尤其是老百姓，与西方文明接触的时候，先接受的都是口语化的东西，因此大家想花费力气翻译个文言文的，却没有白话文的流传广泛。
当时想统一翻译一本圣经，有三个版本都叫和合本。官话和合白板（贩夫走卒），深文理（知识分子），浅文理（念过一些书的）。
非常有趣，官话本后来大家都喜欢。最后只出来一个深文理就算了。几代人努力之后官话本流行起来。
鲍康宁，狄考文，富善。他们把圣经翻译出来了，贡献在哪里。
对于我们学习中文有什么意义？
他们的价值被历史掩盖。他们发现了适合中国百姓的中文的文体，当年的翻译原则可以做为今天的翻译写作原则。
比如富善提出翻译圣经的5项原则要求里提出——
1.译文必须口语化。像英王詹姆士一世的KJV（《英皇钦定版圣经》 也称英王钦定本圣经 或英皇钦定本圣经（Authorized King James Version，简称KJV）400年来英美文学影响最大的一本书。所有人都会看kjv版，虽然现代版出来，很多英文表达和成语都来源于kjv，所以他们想做圣经的中国的詹姆士一世版本。
2.语言必须是普遍通用。今天的翻译一直有个问题，要不要把原文中的比喻弄成中文的比喻。只要做过翻译的人都有这个冲动：比如说曹操，曹操就到，管鲍之交等，猛张飞一样……就会觉得很奇怪，这不是英国人的表达。硬生生这么变，其实破坏了原文别致的美。有跳脱的感觉。
……再举例，现在倡导创业，越来越多的孵化器像雨后春笋样出来，翻译俄罗斯文学就不能这么说，他们没有笋，就说像雨后的蘑菇一样（他们白桦林多），这种语境下我们看到中西文化的碰撞。
他们翻译圣经的时候用到一个办法：在一张纸竖着写出来经文，每个人的修改意见6行6列写旁边。在github上我们就可以做这件事。把不同的译文或者意见，用类似方式呈现出来。
还是举圣经的例子。两个译本：传统和合本，香港的译本。
大家发现用github能完美模拟不同的意见，把不同版本做成两栏，原本是方便程序员做代码方便，现在可以借助过来做文本的修改。几个人和合的结果就能做出大家都满意的版本，复刻了传教士们做圣经的过程。
如果不用网络，自己能否一个人在家和合？可以的。
用文本的工具。分栏查看的功能，可以分成最多4栏，特别适合写稿。参考自己不同的三个版本，再在右边写个新版本，比word来回切换好很多，效率会很高。参照别人的时候效率更高，简直是洗稿利器。
当然这还是表面的，这套东西实际上有更深的用途。你阅读的时候不要当成一个文本，文本都是跨越式的，互联网带来了超文本的概念，实际上点一个连接就离开的也不算超文本，因为离开了这个页面。所以到今天没有东西能代替纸，平面的阅读，摊开后很容易看到全局，任何角落都可以做笔记，感想，文本的融合，把原文本做成超文本，超超文本。这样做最大的好处是你融会贯通了这本书，并创造出神奇的东西。
举个小例子。
编剧故事营。最近在搞教父的剧本和电影。这不是通俗小说，含义非常深刻，有很多值得深入思考的东西。教父的秘密参透后，再来看其他电影就是小菜一碟了。教父在各种电影排行榜前两位。以前一直是第一位的。后来小屁孩们说肖申克救赎好。
跨文本的阅读是产生灵感的源泉。看我的重要私密文件夹透露下。一般人我不告诉他。
绝版秘籍来喽。
教父其实来源于一本小说，作者（马里奥·普佐）想象出来的黑社会。电影剧本是怎么来的，请看大屏幕，一本书上加了很多很多批注，都是导演加的。（弗朗西斯·福特·科波拉）他拿到小说之后，先买两本，裁开，正反面都贴到A4纸上，做出小说版，空白的地方，所有灵感都记录上去，划线，做记号，做批注。这些东西将来做成属于自己的超文本，作用就是工作本。导演用这个导演电影。科波拉既是导演也是编剧。他不用剧本来导演，都是带这个本子，这是他的命，本子上写着，谁捡到了请还回来。绝版。

![《教父》笔记](https://user-images.githubusercontent.com/3174106/32974441-10ee2f1a-cc39-11e7-9487-bf36a05643ca.jpeg)

> 大家看在这页上这么多记号。

![《教父》笔记](https://user-images.githubusercontent.com/3174106/32974432-03b76dde-cc39-11e7-8c06-020ac630c3d1.jpeg)

>因为灵感特别多，是重要的一场戏。全剧的高潮。小儿子麦克在酒吧里射杀警察。
通过这个办法大家可以学到一些工作的方法，就是当买了一本书不要心疼，不舍得往上画。贫困年代的印迹。请尽情的画，你在制作这本自己的书的时候会发生奇妙的事情。科波拉做这个工作本的时候灵感不断的冒出来，一个脑力工作者在做枯燥的体力劳动时会迸发灵感。
找湖南新化人适合做这个，弄成A4，四面弄成空白，好像省力很多。但有个巨大损失，丧失了手工劳动带来的灵感，当你翻来翻去，剪纸，粘贴的时候会扫到文本，好的idea已经发生了。
好多书是不值得大家这样读的，值得反复思考的东西，可以这样做。

## 变更
~ 记录合并学员建议/增补的主要变动信息

- 171118 猛犸 添加图片，修改格式
- 171117 无双 init.
- ... 使用日期 作者 记要 <-- 这种行格式来嗯哼

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by hhztxws** [comment]
似乎不能加图？

**Comment by mammoth2008** [comment]
![如何添加附件](https://user-images.githubusercontent.com/3174106/32974509-a6d9a9a0-cc39-11e7-979c-b943f2675f93.png)

加图的提示

**Comment by seagull0101** [comment]
可以留言了。

**Comment by baibanbao** [comment]
这个缺了两张关键的图，恰恰这两张图构成了这堂课的要件。除非到了正式上课，我是不会放出来的。

**Comment by mengfu1973** [comment]
穷人缺乏想象力，经典。

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
