### ISSUE TITLE
[LOG]好中文群聊要记20171117

### ISSUE THREAD

**Issue by qingkongdy** [GC4WP/common#7]
## 背景
~ 时间：2017.11.11
   内容：好中文群中的部分讨论记要
## 分析
~ 选择记录了两个话题讨论和两个概念介绍
话题讨论1：从菜鸟到大神
话题讨论2：什么才是故事永恒的主题
概念介绍1：心理学基础知识——投射
概念介绍2：知识的非线性

## 记录

**话题讨论1：从菜鸟到大神**

由@夏唸薇 发感群里都是大神开启。

@我思故我在 和@湛江 强调不要自我设限，再牛逼的人都是从菜鸟过来的，虽有像笛卡尔这样的天才，但毕竟是少数，绝大多数还是通过日积月累的勤奋成功的。

@花无双 提出一个观点：某个领域的大神有可能在其他领域是菜鸟，菜不菜，相对看。

@湛江 最开始的起跑线上差异不会太大，离起跑线越远差异越大，不过，开始了就是好的。每个人都是菜鸟与大神的复合体。

@夏唸薇 我也菜鸟，以前就是听电台广播，常年去看人家文圈的朋友写文字，我把我看到了听到集合组成了很多故事。然后就在贴吧写了些美文，不过粉丝只局限在学生块。后来到了简书就开始写干货，原来学广告设计做些关于简书排版教程，之后就是做一些本行的摄影志，写自己家乡收到过简叔赞赏。后来就开始写身边人故事，点击率还是不比干货高，偶尔有几篇文章被人赞赏，虽然偿到了一点甜头但是坚持下去很难睡得太晚。后来又出去上班文字被批惨状连连的。有点荒废了。之前还给简书老师做过平面设计助理，二维码设计还是不错的。偶然一天我主管发现我剧本才能，我比他的学员早早学完，我花了半天，时间就完成了，而他们一天左右。她鼓励我做写手，才加入简书的。

各位有空来柳州请你们吃螺蛳粉。（反正我是记下了）

***********************************************************************************

**话题讨论2：什么才是故事永恒的主题**

由@大妈 谈故事力开启。

@大妈 ：
如文案真正价值所在
文字真正作用成份是 故事
为何人类对故事痴迷?
人类简史中有述 不在此摘抄

单猜此曰 故事力
很形象指出故事不同
穿透人心深度也必然不同
为何?

故事千变万化
然动人心魄 只能是读者心中已有之物之情之缺乏
否则 若
无根之水 
无接口之黑箱系统
已死之人
绝无一丝触动可能

然人和人岁齿越长
经历越多
内心戏越不同

什么故事能通吃所有读者?
爱情和战争是永恒主题
点解?

唯有所有人
所有层次文化性别民族肤色之人
皆不得不关注主题
由此演化而成故事
其穿透力最大
引爆共呜越深

因为人之所以为人
就是由一组共同且有别其它物种关注之事由在万千世界中各自历练而成
表面看起来难有相同
 --> 即便双胞胎 长成后也有越来越多差异点
但内在 有严密相同之大恐怖

将此组大恐怖合理推衍幻化
嵌入各种场景中
以幸存者姿态小意描述回来

感动
感触
感想
感慨…等等

必然由读者下意识自动涌动

其力甚伟
无从力敌
故事力透
穿魂碎魄 

是也乎 ╮(╯▽╰)╭

当然此伟力乍修炼?
佩哥哥有招
俺无招
猛玛有奶

关爱瓜瓜
人人有责

@我思故我在 引发所有人共鸣的，是对死亡的恐惧。人类的一切思想行为乃至整个文明的建立，都源于恐惧这种最原始的情感。我们都是爬在文明之网上的虫子，带着掉下去的恐惧往上爬。

@醉舟 爱情和战争说法太文艺，简单点是性和暴力……无论何时何地，性和暴力是人类永恒的主题。

@野树 性和暴力是人类永恒的主题[惊讶][惊讶] 传世经典可不宣扬性和暴力。活塞运动和打打杀杀，几下子就腻，永恒得起来吗。   爱和自由是永恒主题—树的看法。

@鲁锋 爱情与苦难。

@逆行的水星 人与人性才是永恒的主题。

***********************************************************************************

**概念介绍1：心理学基础知识——投射**

@野树 讲到了一个重要的心理学基础知识——投射。

投射法是以弗洛伊德心理分析的人格理论为依据，强调人的行为由无意识的内驱力所推动， 一般是由若干个模棱两可的刺激所组成，被试可任加解释，使自己的动机、态度、感情以及 性格等在不知不觉中反应出来，然后由主试将其反应加以分析，就可以退出若干人格特征。人们在日常生活中常常不自觉的把自己的心理特征（如个性、好恶、欲望、观念、情绪等）归属到别人身上，认为别人也具有同样的特征，如：自己喜欢说谎，就认为别人也总是在骗自己；自己自我感觉良好，就认为别人也都认为自己很出色……心理学家们称这种心理现象为"投射效应"。

投射是人们常常无意识地把自己的心理特征，思维方式，情绪归属到别人身上，以自己的心理去揣度别人的心理，认为别人也应该有和自己同样的特征。如秦二世的时候，宰相赵高掌握了朝政大权。他因为害怕群臣中有人不服，就想了一个主意。有一天上朝时，他牵着一只梅花鹿对二世说：“陛下，这是我献的名马，它一天能走一千里，一夜能走八百里。”二世听了，大笑说：“承相啊，这明明是一只鹿，你却说是马，真是错得太离谱了!”赵高说：“这确实是一匹马，陛下怎么说是鹿呢?”二世觉得纳闷，就让群臣百官来评判。大家心想，说实话会得罪承相，说假话又怕欺骗陛下，就都不出声。这时赵高盯着群臣，指着鹿大声问：“大家看，这样身圆腿瘦，耳尖尾粗，不是马是甚么?”大家都害怕赵高的势力，知道不说不行，就都说是马，赵高非常得意，二世被弄胡涂了，明明是鹿，怎么大家都说是马呢?他以为自己疯了，从此越来越胡涂，朝政上的事都完全由赵高来操纵。　　赵高暗中把那些说实话的人杀掉，又派人杀死二世，霸占整个朝廷，最后终于导致秦朝灭亡。指鹿为马就是投射法的例子之一。

这个世界虽然是客观的，但是所有你看到的、听到的、感受到的东西，经过你的心理加工，都不可避免、或多或少地包含了主观的成分。孕妇效应相信大家都听说过，就是当你怀孕了，你会突然发现身边多了好多孕妇；你开了奔驰，然后发生朝你驶来的好多车都是奔驰；你拎了个LV，于是发现满大街的人拎的都是LV。孕妇效应其实就是一个很典型的投射效应。其实并不是突然间多了那么多和你一样的人。某一部分人的比例一直都是比较稳定的，只是当你不怎么在意的时候，你常常把它们过滤忽视掉了，或是即使注意到了也很快就把它们忘记了。当你关注之后，它们会给你留下了很深的印象，所以你会觉得很多。而你所关注的，恰恰就反映了你的内心。当你特别在意（可能是你拥有的，也可能是你渴望而不可得的）某些东西的时候，你会非常关注它。荣格提出了“情结”这一概念，他认为，内在有什么情结，外在就会被什么吸引。而一些触碰到情结的东西，会引发外显的行为。他设计的语词联想测验是最早的心理学投射测验之一。测试的方法很简单，给你一个词，你尽快回答一个联想到的词。咨询师会记录你的用时和给出的对应词，然后进行分析。

荣格曾给一位三十五岁的正派人士做了语词联想测验，结果发现了他的一个秘密。荣格说：“对不起，我不知道你曾有过如此不愉快的经历。”被试人盯着荣格说：“我不知道你在说些什么。荣格说：“你知道，你曾喝醉酒，有一桩以刀伤人的不愉快的纠葛。”被试人说：“你是怎么知道的？！”随后供出了整个事情的经过。他出身于一户受人尊重的正派家庭，他曾出过国。有一天因喝醉酒与人发生争吵，便用刀刺伤了对方，结果蹲了一年牢房。来到本地后没人知道这件事，而荣格是唯一破解此事的人。因为荣格发现他对“刀”、“矛”、“打”、“尖锐的”、“瓶”这五个词的反应时超过平均反应时很多。对“刀”、“矛”反应时延长，看来这件事与刀有关，应该使用了刀。而“尖锐的”既可涉及瓶，又可涉及刀。有刀、有瓶，刀用于伤人，瓶干什么？应该是酒瓶，是喝酒时伤人。打，应该是打人、打架。虽然只是几个词，但足以把被试人的内在情结表现出来。

如果有人说你什么，说的不是“你”，是他心里的“投射”；如果在好中文群，有人怼你，怼的也不是你，怼的是他心里的“投射”；世界、他人都是镜子，这就是一个镜像世界。旁边坐一个异性老外，说“我要跟你有关系” ，中国人会笑，老外不会笑。老外心里没有，中国人心里有。

***********************************************************************************

**概念介绍2：知识的非线性**

@王佩 老师提出这一概念，@大妈 详解。

@大妈 ：
现在我们一问一答
象一根线上的蚂蚱
所以, 称线性...

非线性, 即异步...
好比, 你写信给俺, 然后就结婚生子去了,
俺42年后从天狼星回你的信,
继续那几个问答....
就是非线性

@花无双 ：
我们宝妈群就是非线性的

@行藏 ：
咋感觉和主妇聊天模式异曲同工

@花无双 ：
是啊，这边聊幼儿园那边还有人在讲今天怎么生病了，还有人去睡觉喂孩子了，忙完上来继续说幼儿园，多线程。

@大妈 ：
进一步的, 线性也包含了场所的相同
虽然在微信群中好象隔了很远才回答
不是线性
其实, 因为所有对话发生在相同的群场景中
而且存储介质也相同
从技术上可以视作是线性的

严格意义上的非线性,
字面上理解就是, 不在同一根线上
这线不仅仅指时间线,
还指空间/情绪/等等....

比如传统的信件,
双方在回复信件时, 所在时空间都是不相同的,
所以信件中需要用额外的篇幅来还原写信时的场景,
就是为了帮助对方以及自己来保持在一个相对固定的线索上...

这也是 信息简史 (豆瓣) 
    https://book.douban.com/subject/25752043/
中发现的信息压缩有极限的原因所在

非线性交流的意义：

既然 非线性交流这么困难
为毛 IM ~ 即时通讯, 线性交流不是大规模沟通的主流?
参考:人类简史 (豆瓣) 
    https://book.douban.com/subject/25985021/
f2f ~ face to face 当面沟通的效率看起来高
但是,对应的成本也异常的高
在文字发明前, 最大的部落也无法超过 150 人
就是因为想让一件事儿,令全体知道的成本是随着必须沟通的人数增加而指数增加的;
A->B
B->A
两人沟通, 一来一去,即可完成信息的发送/接收/检验

3人时要进行多少次的传递?
ABC
ACB
BAC
BCA
CAB
CBA
变成6次, 计算式其实就是 P3 ~排列组合

150人要完成的沟通量已经超过一周时, 这导致很多有实时要求的协作无法进行...

怎么办? 异步, 通过文字, 各自并行理解/执行/交互/改进....
是的, 将主妇流式异步沟通放大到社会所有层面上,
这, 就是现代社会的协作基础...

@猛犸 ：
也是为什么推荐使用github的原因

@行藏 ：
大妈的讲解唤醒了我脑内存储的管理学原理关于组织内部正式沟通的网络形态的记忆 全通道式沟通应该就是非线性沟通 

## 变更
~ 记录合并学员建议/增补的主要变动信息

201171117
整理员：青空

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

tags: [5:logging]

**Comment by qingkongdy** [comment]
tags:
- 5:logging 
- good first issue

**Comment by qingkongdy** [comment]
tags: [5:logging]

**Comment by seagull0101** [comment]
谢谢青空同学的记录。

**Comment by ZoomQuiet** [comment]
ARCHIVED be wiki ;-) 归档/收录/提交ed
