### ISSUE TITLE
进入仓库资料填写

### ISSUE THREAD

**Issue by Hansoluo** [GC4WP/common#9]
## 背景
- 猛犸兄不辞辛苦在群里发送邀请，特此感谢
- 如果有同学没有被邀请，或者邀请了没进入仓库，可以在该issue下面填写自己的信息和状态

## 填写资料

序号|微信昵称|用户名|邮件|是否已进入仓库
-------|--|-----|---|----
1|醉舟|hansoluo|shy757@126.com| 已进入

- 目前没进入仓库的同学不可以编辑本issue，但是可以在下面回复
- 可以按上述格式填写
- 状态有“待邀请”“已邀请”“已进入”“出现错误”四类

## changelog
- 171117 ZQ init.
- ... 使用日期 作者 记要 <-- 这种行格式来嗯哼

```
 .
  .
...
```
参考: [禁止事项清单](https://github.com/GC4WP/common/wiki/HbNotDoIt)

**Comment by carolhe1977** [comment]
清风｜ carolhe1977  | 359636528.qq.com | 已进入

**Comment by chmcelia** [comment]
风起｜chmcelia｜1376719201@qq.com｜已进入
